id: P43C52BF5
initial_creation_type: input
source_metadata:
  Title: Nārāyaṇaparipṛcchā sutra
  Editor: Banerjee, A.C.
  Publisher: University of Calcutta
  Place of Publication: Calcutta
  Year: '1941'
  Nārāyaṇaparipṛcchā āryamahāmāyāvijayavāhinī nāma dhāraṇī:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:57:01.054185'
last_modified_at: '2022-03-08T15:57:01.054193'
